spring:
  profiles:
    active: stress

---
spring:
  output:
    ansi:
      enabled: always
  application:
    name: webflux-coroutine
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
logging:
  level:
    com.study: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/sample
  sql:
    init:
      mode: always
---
spring:
  config:
    activate:
      on-profile: stress
  sql:
    init:
      mode: never
logging:
  level:
    com.study: debug
    org.springframework.r2dbc.core: off
    org.springframework.r2dbc.connection.init: off